language: ruby
cache: bundler
sudo: false
rvm:
- 2.1.3
before_script:
- bundle exec rake db:create && bundle exec rake db:migrate
notifications:
  irc:
    channels:
    - irc.freenode.net#openaddresses
    template:
    - "%{repository} %{branch} - %{message} %{build_url}"
    on_success: change
    on_failure: always
deploy:
  provider: heroku
  strategy: api
  api_key:
    secure: OJbpmEllpiolSqG5eB1hqgRTe4/w9F9njXlmUTsvWC7uBpff/63KJDKDPM0px0PzERlo5bU47ifwnhSRTEz/ObbMd9gjzafTDskIWY4qFumN3Eufu6fgmTC23ztroUjNQWD7miOLq8JH3erPME+4okSRIULMMrchmEzkjmqmHNU=
  app: shrouded-caverns-1022
  run:
  - rake db:migrate
  on:
    repo: OpenAddressesUK/ernest
env:
  global:
  - secure: iyMNyqvrwIgEA0C/0lkuFrUe97AlY54I95C9KTzw5uYiVdTIPM0SMRM6GJkoOcsOzereniLJrPv1wtj9llGITvdX5vA8vq+2JUKrKg18zo/u6rcUaVBzXzvjCVnEhAOzeHOzw4FSrQQfYf9hoa0XP33ILSig/YdWNQ4fi8aRAEQ=
  - secure: XjmBxNS/ly0mYy2CBEWrgVgwWtEhqJptSSDMYtPfhF7Y2qNuUMJqGLKRFHwSRDstw00BJGYCKdo0eB3aU/UzIrgN0RguHwO1uRL8Wqei/vHTes7IYI4gGPk0f8E8UwHpHLvtSva/TIyByeAoBUO9goAc3pSI6PmFpdwz438aepg=
  - secure: OPlx6PJC6fHHFaUNSVzXkRoxXXTLCrOUYRSAC3H6FDBOPBaoYfdKP35NdIx2jv0eUCVjykE5NQS56aN7S1shUHYnu8bnHYyUgAmTMXo8/anjY/QPRAnYe2U9lpS3G1P0mJm4f3tJj2umIDHA03s5JO3ilP/kmhSTFuVBL4F4WZ8=
