development:
  adapter: mysql2spatial
  encoding: utf8
  database: ernest_development
  pool: 5
  host: 127.0.0.1
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2spatial
  encoding: utf8
  database: ernest_test
  pool: 5
  host: 127.0.0.1
  username: root
  password:
  socket: /tmp/mysql.sock
